### PR TITLE
Implementation of m:wtable tag

### PR DESCRIPTION
**Pull request by ldelaigue**

### CODE REVIEW

**Comment by ldelaigue** [comment]
The build failed because of a time-out when connecting with the eclipse Luna update site... Is it possible to retrigger the build?

**Comment by ylussaud** [comment]
done. on the top right side of the travis build page.

**Comment by ohaegi** [comment]
In plug-in example "org.obeonetwork.m2doc.ecore.wtable.test",  the genconf models can't be open in Model Explorer view. This is cause by a bad semanticResources setting in file representations.aird. We should put  that : 
   <semanticResources>testValidTables.genconf</semanticResources>
  <semanticResources>testInvalidTags.genconf</semanticResources>
not that
  <semanticResources>templateTest.genconf</semanticResources>

**Comment by ohaegi** [comment]
I  built the update site with maven ("mvn clen verify" command in "releng/org.obeonetwork.m2doc.parent/" project), i installed the new  M2Doc update site  in a eclipse bundle (ObeoDesigner-Community-8.1 bundle exactly) and I generated  the documentation examples in  "org.obeonetwork.m2doc.ecore.wtable.test". 
The generated files are same than expected files (with word compare tool).

The wtable feature support seems working.

**Comment by ldelaigue** [comment]
I have pushed 2 commits:
- Extracted inner class TableClientProcessor
- Added unit tests
- Fixed the set-up of the Sirius test project so that the templates are imported into the Sirius session
- Renamed the expected files so that it's easier to validate

**Pull request merged**
